### ISSUE TITLE
导入maven后无法实现VScene的子类

### ISSUE THREAD

**Issue by ldj2020** [wkgcass/vfx#2]
VScene的子类的构造方法内的io.vproxy.vfx.ui.scene.VSceneRole非暴露出来无法调用

![image](https://github.com/wkgcass/vfx/assets/61624586/eb88568c-4f33-4bd2-b554-c1e502a59848)

>

**Comment by wkgcass** [comment]
应该没问题吧：
https://github.com/wkgcass/vfx/blob/master/src/main/java/io/vproxy/vfx/ui/scene/VSceneRole.java
这是public enum

https://github.com/wkgcass/vfx/blob/master/src/main/java/module-info.java
这里也export了

换README里的最新版试试

**Comment by ldj2020** [comment]
需要导入1.3.4版本，才可以调用VSceneRole
```
<dependency>
            <groupId>io.vproxy</groupId>
            <artifactId>vfx</artifactId>
            <version>1.3.4</version>
        </dependency>
```
1.3.5的包结构如下
![image](https://github.com/wkgcass/vfx/assets/61624586/f66625ae-b5ab-47db-8412-cd33ecce0f04)
1.3.4的包结构如下
![image](https://github.com/wkgcass/vfx/assets/61624586/1304bc90-539d-45ff-b37d-9a08104a38f8)

**Comment by wkgcass** [comment]
master分支都已经`1.3.5`了，能不能看一眼
