### ISSUE TITLE
大佬您不写注释，我太菜了看不懂😭

### ISSUE THREAD

**Issue by yranium2023** [wkgcass/vfx#3]

**Comment by wkgcass** [comment]
那我有空写个文档吧。。。

**Comment by yranium2023** [comment]
好诶，谢谢大佬🥹

**Comment by yranium2023** [comment]
非常感谢您能够开源这样一套精美的UI
这是我们用它做出来的一个小项目<https://github.com/yranium2023/LightStudioClassic>
刚学了3个月java，写起来非常的不优雅😇不过最后的呈现效果很不错
非常感谢您！
